### ISSUE TITLE
Disabling Hitsounds/Effects

### ISSUE THREAD

**Issue by LordDamionDevil** [DevEkode/osu-replayViewer-web#61]
**Is your feature request related to a problem? Please describe.**
Not really, this is more based on the choice of the Beatmap and if the Player wants it or not.

**Describe the solution you'd like**
Disabling the general Hitsounds (This can be done by making Effects Volume 0%) or just from the beatmap which is done via disable beatmap hitsounds.
Link to a Reddit post talking about it: [Click Me](https://www.reddit.com/r/osugame/comments/4n9oz9/some_beatmaps_ignore_disable_beatmap_hitsounds/
)

This could be done by adding a slider or radio system with three options (Normal, No Custom Hitsounds, Off)

**Additional context**
I just posted this cause two people requested it on the discord.

**Comment by DevEkode** [comment]
Added in v0.2.3
