### ISSUE TITLE
Ignoring invalid mod combo replays

### ISSUE THREAD

**Issue by SpeckyYT** [DevEkode/osu-replayViewer-web#65]
**Is your feature request related to a problem? Please describe.**
When uploading a replay with impossible mod combos (like HDDT / PFNF / EZHR) the replay gets recorded anyways.
(example https://osureplayviewer.xyz/view.php?id=5d71336988171)

**Describe the solution you'd like**
It would be nice if the replay would get stopped at the first step after uploading it.

**Comment by DevEkode** [comment]
Fixed in last develop commit
