### ISSUE TITLE
Replay not being processed? 

### ISSUE THREAD

**Issue by eax-hash** [DevEkode/osu-replayViewer-web#72]
https://i.imgur.com/rASInhJ.png
https://i.imgur.com/NobZZZr.png
Every replay says an different position in the queue, and it never changes.
Is there something wrong atm?

**Comment by SpeckyYT** [comment]
It's normal that different replays have different positions inside of a queue.
It looks like there are sometimes issues with Osu, and that's why the replays get sometimes stuck.

**Comment by DevEkode** [comment]
Yeah. It can happen, I'm trying to make the queue as stable as possible but it's not easy. I'll keep the issue open and tag it "to improve" and will make updates here when I fix a huge issue.
