### ISSUE TITLE
"This replay has been waiting" is one hour ahead.

### ISSUE THREAD

**Issue by SpeckyYT** [DevEkode/osu-replayViewer-web#75]
**Describe the bug**
"This replay has been waiting :" on the  is one hour ahead of when you uploaded the replay.

**To Reproduce**
1. Go to https://osureplayviewer.xyz/index.php
2. Drag and drop your replay on the replay upload area in the page.
3. Accept all ToS stuff.
4. Once you uploaded it, you should see error on the replay status page.

**Expected behavior**
Time should be starting at 0d 0h 0m 0s

**Screenshots**
![image](https://user-images.githubusercontent.com/40666126/68607763-af993f80-04b1-11ea-86f3-37fd00875976.png)

**Desktop**
 - Browser [Google Chrome]

**Extra Informations**
Replay was uploaded at ~6:30PM (CET)

**Comment by DevEkode** [comment]
I need to make a fix for winter hours
