### ISSUE TITLE
[REQUEST] Web JSON API of users and replays

### ISSUE THREAD

**Issue by SpeckyYT** [DevEkode/osu-replayViewer-web#83]
**Is your feature request related to a problem? Please describe.**
It would be nice to have API data of the website.

**Describe the solution you'd like**
JSON example when searching "https://api.osureplayviewer.xyz/userProfile.php?id=11630662"
```
{
        "5dcc686ccaa77": {                            //ReplayID
            "Title": "Sunglow",
            "Author": "Yamajet",
            "Source": "crossbeats REV. SUNRISE",
            "etc":"etc",  
            "Difficulty": {
                "Mode": 0,
                "Stars": 5.89,
                "Name" : "Melody",
                "CS": 4,
                "AR": 9.7,
                "etc":"etc"
            },
            "Replay":{
                "Score": 879270,
                "300": 675,
                "Geki": 82,
                "100": 314,
                "Katsu": 130,
                "50": 59,
                "Misses": 191,
                "maxCombo": 78,
                "accuracy": 63.72
            }
        }
    },
    "5dc31485eb164": {
        "Title": "Yoru no Kodomo tachi",
        "Author": "Roses Epicurean",
        "Source": null,
        "etc":"etc",  
        "Difficulty": {
            "Mode": 0,
            "Stars": 4.28,
            "Name" : "Hard",
            "CS": 3.5,
            "AR": 8.5,
            "etc":"etc"
        },
        "Replay":{
            "Score": 613045,
            "300": 119,
            "Geki": 36,
            "100": 0,
            "Katsu": 0,
            "50": 0,
            "Misses": 0,
            "maxCombo": 168,
            "accuracy": 100.00
        }
}
```

**Additional context**
Would be nice if there would be a page where you can search a user by name in the link (https://api.osureplayviewer.xyz/search.php?input="SpeckyYT"  [which would return:] https://api.osureplayviewer.xyz/userProfile.php?id=11630662)

**Comment by LordDamionDevil** [comment]
I think it would be better to switch the id out with the title so you can more easily use the json api to make a search system for mass search without having to make it too complex also the Search for user should return a JSON array/table with the username, id and some more info about the user.

**Comment by SpeckyYT** [comment]
It was only an example, it can be changed on decisions of the devs at any times.

**Comment by DevEkode** [comment]
Great idea, I'll keep this for the v2.
